language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "spyql-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: spyql
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: vuYsPAYBYupZL01RIEwE9+TXq4vOobK42z6v9Y754vRne52FOugVEdtPNHPRggFl3YErwyYleNpWtEtdKBBi6+J0nd/sVu/ESuz4wkrrEBNB/nbA2GV3Trb4OWVR+E8CA/Xc27DAU3JZdAYiIBtRkYECjNKziDe7OuPAeCrWNezU9+jlCgZXMifhHuNX7wZbxMiOAyYiIOKCasjANjVTlT9OmAw/OnOt1UT/GFCsIaAXKsiMuA2Nh/Irx4BpXIA7xP5vS/S5IFSbnR0AZEyaTRCEYXKVH1mgqQUUcjMI1ezN56boc7gZLraflueABoDH38JWaYi+2L2wZIZAO2VQB33txZRK0THMk4hFevUwqDXb2iTsFXigaDBGGmkWktdqWWPp8K89zfleDLbGjMtj2JEVWeLRelCxS6+cGjhzYK9OJ7CurXrXOG4WOH7wsCPTUM4wmmFkc+3wJeNjMGaUyMmhU0sbudMgTftyIljdxSg0yTCeAynTXEl0BqajGMvR4cxiPWp/VG5bZR3kXcWXR7kUXjsMKrRLUQlb4Hk8iM3RwoKk/Ql5XHhXr55gG9aXseSNwb5byapeSuqZkXgrZHpkRaJHvlvVWhfrctf5Psrxlr7gqEYzK1Paocf+bfzBo3BDplRq/3YWrpdSQOGP+j23zcSUiK2dw5vKfGAaFg4=
